name: Tweet paper acceptance
description: Send a tweet announcing a new published paper
inputs:
  journal_name:
    description: The name of the journal
    required: true
  paper_title:
    description: The title of the accepted paper
    required: true
  paper_doi:
    description: The DOI of the accepted paper
    required: true
  twitter_consumer_key:
    description: Twitter consumer key
    required: false
  twitter_consumer_secret:
    description: Twitter consumer secret
    required: true
  twitter_access_token:
    description: Twitter access token
    required: true
  twitter_access_token_secret:
    description: Twitter access token secret
    required: true
  reviews_repo:
    description: The repository containing the review issue for the paper
    required: true
  issue_id:
    description: The issue number of the submission (to post a link to the tweet)
    required: true
  gh_token:
    description: The github token to use for replying to the review issue
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true
        cache-version: acceptance-tweet
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Tweet paper
      id: send-tweet
      shell: bash
      env:
        JOURNAL_NAME: ${{ inputs.journal_name }}
        PAPER_TITLE: ${{ inputs.paper_title }}
        PAPER_DOI: ${{ inputs.paper_doi }}
        TWITTER_CONSUMER_KEY: ${{ inputs.twitter_consumer_key }}
        TWITTER_CONSUMER_SECRET: ${{ inputs.twitter_consumer_secret }}
        TWITTER_ACCESS_TOKEN: ${{ inputs.twitter_access_token }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ inputs.twitter_access_token_secret }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/tweet_acceptance.rb
    - name: Comment
      if: ${{ steps.send-tweet.tweet_result == 'ok' }}
      shell: bash
      run: |
        gh issue comment ${{ inputs.issue_id }} --body "🐦🐦🐦 👉 [Tweet for this paper](${{ steps.send-tweet.tweet_url }}) 👈 🐦🐦🐦"
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        GH_REPO: ${{ inputs.reviews_repo }}
branding:
  icon: twitter
  color: blue
